### PR TITLE
Fix turn challenge usable cards

### LINKED ISSUE #13: todo: rule: 4 card skips opponent turn

### PR DESCRIPTION
**Pull request by mirceanis**
fixes #13 ?

### CODE REVIEW

File: app/src/main/java/com/sound/keloomacaua/game/CardMoves.java [hunk 1]
```diff
@@ -220,14 +220,16 @@ public boolean canPlayCard(int card) {
         int topCard = getTopCard();
 
         boolean isChallengeCard = challengeCards.contains(getCardRank(card));
-        boolean correctChallenge = (game.owedCards == 0 || isChallengeCard) || (isChallengedToSkip() && cardHasRank(card, CARD_FOUR));
+        boolean correctChallenge = (game.owedCards == 0 || isChallengeCard);
```
Comment (mirceanis) [inline app/src/main/java/com/sound/keloomacaua/game/CardMoves.java:223]: this line and L231 were causing challenged opponent to be able to play any card
